import type {Metadata} from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className="grid min-h-screen grid-rows-[60px,1fr,60px] gap-12">
        <header className="m-auto w-full max-w-screen-lg">
          <nav>Libros</nav>
        </header>
        <main className="m-auto flex h-full  w-full max-w-screen-lg flex-col items-center justify-between">
          {children}
        </main>
        <footer className="m-auto w-full max-w-screen-lg text-center">
          Hecho con ❤ por Goncy
        </footer>
      </body>
    </html>
  );
}
